# Prometheus alert rules for Robo Trader
# Critical alerts for trading system reliability

groups:
  - name: robo_trader_alerts
    rules:
      # Service availability alerts
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          category: availability
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 1 minute."

      - alert: ServiceRestarted
        expr: up == 1 and increase(up[5m]) > 0
        for: 5m
        labels:
          severity: warning
          category: availability
        annotations:
          summary: "Service {{ $labels.job }} restarted"
          description: "Service {{ $labels.job }} has restarted in the last 5 minutes."

      # Performance alerts
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
          category: performance
        annotations:
          summary: "High response time on {{ $labels.job }}"
          description: "95th percentile response time > 2s for {{ $labels.job }}"

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 2m
        labels:
          severity: critical
          category: errors
        annotations:
          summary: "High error rate on {{ $labels.job }}"
          description: "Error rate > 5% for {{ $labels.job }} in the last 2 minutes"

      # Trading-specific alerts
      - alert: PortfolioServiceDown
        expr: up{job="portfolio-service"} == 0
        for: 30s
        labels:
          severity: critical
          category: trading
        annotations:
          summary: "Portfolio service is down"
          description: "Portfolio service unavailable - trading operations may be affected"

      - alert: RiskServiceDown
        expr: up{job="risk-service"} == 0
        for: 30s
        labels:
          severity: critical
          category: trading
        annotations:
          summary: "Risk service is down"
          description: "Risk management unavailable - trading safety compromised"

      - alert: ExecutionServiceDown
        expr: up{job="execution-service"} == 0
        for: 1m
        labels:
          severity: critical
          category: trading
        annotations:
          summary: "Execution service is down"
          description: "Order execution unavailable - immediate attention required"

      # Job queue alerts
      - alert: JobQueueBacklog
        expr: celery_active_tasks > 50
        for: 5m
        labels:
          severity: warning
          category: performance
        annotations:
          summary: "Job queue backlog"
          description: "More than 50 active tasks in job queue"

      - alert: JobQueueFailed
        expr: increase(celery_task_failed_total[10m]) > 10
        for: 5m
        labels:
          severity: warning
          category: errors
        annotations:
          summary: "High job failure rate"
          description: "More than 10 job failures in the last 10 minutes"

      # Database alerts
      - alert: DatabaseDown
        expr: up{job="timescale-db"} == 0
        for: 1m
        labels:
          severity: critical
          category: infrastructure
        annotations:
          summary: "TimescaleDB is down"
          description: "Time-series database unavailable - market data storage affected"

      - alert: DatabaseHighConnections
        expr: pg_stat_activity_count > 80
        for: 5m
        labels:
          severity: warning
          category: performance
        annotations:
          summary: "High database connections"
          description: "Database has more than 80 active connections"

      # Cache alerts
      - alert: RedisDown
        expr: up{job="redis-cache"} == 0
        for: 1m
        labels:
          severity: critical
          category: infrastructure
        annotations:
          summary: "Redis cache is down"
          description: "Caching layer unavailable - performance impact expected"

      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          category: performance
        annotations:
          summary: "Redis high memory usage"
          description: "Redis memory usage > 90%"

      # Event bus alerts
      - alert: EventBusDown
        expr: up{job="event-bus"} == 0
        for: 30s
        labels:
          severity: critical
          category: infrastructure
        annotations:
          summary: "Event bus is down"
          description: "Service communication disrupted - system isolation risk"

      - alert: HighEventBacklog
        expr: event_bus_pending_events > 1000
        for: 2m
        labels:
          severity: warning
          category: performance
        annotations:
          summary: "High event backlog"
          description: "More than 1000 pending events in event bus"

      # Safety layer alerts
      - alert: SafetyLayerDown
        expr: up{job="safety-layer"} == 0
        for: 30s
        labels:
          severity: critical
          category: safety
        annotations:
          summary: "Safety layer is down"
          description: "Compliance and safety monitoring unavailable"

      - alert: CircuitBreakerTripped
        expr: safety_circuit_breaker_state == 1
        for: 1m
        labels:
          severity: warning
          category: safety
        annotations:
          summary: "Circuit breaker tripped"
          description: "Safety circuit breaker activated - trading paused"