#!/usr/bin/env python3
"""
API Test Generator for Robo Trader
Automatically generates pytest tests by parsing route files
"""

import ast
import json
import sys
from pathlib import Path
from typing import List, Dict, Tuple

# Project root
PROJECT_ROOT = Path("/Users/gurusharan/Documents/remote-claude/robo-trader")


class RouteParser:
    """Parse FastAPI route files to extract endpoints"""

    def __init__(self, routes_dir: Path):
        self.routes_dir = routes_dir
        self.endpoints = []

    def parse_file(self, file_path: Path) -> List[Dict]:
        """Parse a single route file"""
        endpoints = []

        try:
            with open(file_path, 'r') as f:
                tree = ast.parse(f.read())

            # Check module-level functions (both sync and async)
            for node in tree.body:
                if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    # Look for route decorators
                    for decorator in node.decorator_list:
                        endpoint = self._parse_decorator(decorator, node)
                        if endpoint:
                            endpoint["file"] = str(file_path.relative_to(PROJECT_ROOT))
                            endpoints.append(endpoint)
                            break  # Only take first matching decorator

        except Exception as e:
            print(f"Error parsing {file_path}: {e}")

        return endpoints

    def _parse_decorator(self, decorator: ast.expr, func: ast.FunctionDef) -> Dict:
        """Parse a decorator to extract route information"""
        # Handle @router.get(), @router.post(), etc.
        if isinstance(decorator, ast.Call):
            if isinstance(decorator.func, ast.Attribute):
                if decorator.func.attr in ['get', 'post', 'put', 'delete', 'patch']:
                    method = decorator.func.attr.upper()

                    # Extract path from first argument
                    path = None
                    if decorator.args:
                        if isinstance(decorator.args[0], ast.Constant):
                            path = decorator.args[0].value

                    if path:
                        # Extract parameters from function signature
                        params = []
                        for arg in func.args.args:
                            if arg.arg not in ['request', 'db', 'container']:
                                params.append(arg.arg)

                        return {
                            "method": method,
                            "path": path,
                            "function": func.name,
                            "params": params
                        }

        return None

    def parse_all(self) -> List[Dict]:
        """Parse all route files"""
        route_files = list(self.routes_dir.glob("**/*.py"))

        for file_path in route_files:
            if file_path.name != "__init__.py":
                endpoints = self.parse_file(file_path)
                self.endpoints.extend(endpoints)

        return self.endpoints


class TestGenerator:
    """Generate pytest tests from endpoint definitions"""

    def __init__(self, endpoints: List[Dict]):
        self.endpoints = endpoints

    def generate_test_function(self, endpoint: Dict) -> str:
        """Generate a single test function"""
        # Create test name
        test_name = f"test_{endpoint['function']}"

        # Create test body
        method = endpoint["method"].lower()
        path = endpoint["path"]

        # Handle path parameters
        if "{" in path:
            # Replace path parameters with sample values
            path = path.replace("{symbol}", "AAPL")
            path = path.replace("{id}", "1")
            path = path.replace("{task_id}", "123")

        # Build request
        if method in ["get", "delete"]:
            request_line = f'    response = client.{method}(f"{{BASE_URL}}{path}", timeout=5)'
        else:
            # POST/PUT/PATCH need a body
            request_line = f'    response = client.{method}(f"{{BASE_URL}}{path}", json={{}}, timeout=5)'

        test_code = f'''def {test_name}(client, BASE_URL):
    """Test {endpoint["method"]} {endpoint["path"]}"""
{request_line}
    assert response.status_code in [200, 201, 204, 404], f"Unexpected status: {{response.status_code}}"
    # 404 is acceptable for endpoints that require specific data
    if response.status_code != 404:
        assert isinstance(response.json(), (dict, list))
'''

        return test_code

    def generate_test_file(self) -> str:
        """Generate complete test file"""
        header = '''"""
Auto-generated API tests
Generated by api-test-generator.py
"""

import pytest
import httpx


@pytest.fixture
def client():
    """HTTP client fixture"""
    return httpx.Client()


@pytest.fixture
def BASE_URL():
    """Base URL fixture"""
    return "http://localhost:8000"


# ============================================================
# Generated Tests
# ============================================================

'''

        test_functions = []
        for endpoint in self.endpoints:
            test_func = self.generate_test_function(endpoint)
            test_functions.append(test_func)

        return header + "\n\n".join(test_functions)


def main():
    print("=" * 60)
    print("API Test Generator Starting")
    print("=" * 60)

    # Parse routes
    routes_dir = PROJECT_ROOT / "src/web/routes"
    parser = RouteParser(routes_dir)
    endpoints = parser.parse_all()

    print(f"\nFound {len(endpoints)} endpoints:")
    for endpoint in endpoints:
        print(f"  {endpoint['method']:6} {endpoint['path']:40} ({endpoint['file']})")

    # Generate tests
    generator = TestGenerator(endpoints)
    test_code = generator.generate_test_file()

    # Write test file
    test_dir = PROJECT_ROOT / "tests/api"
    test_dir.mkdir(parents=True, exist_ok=True)

    test_file = test_dir / "test_generated_endpoints.py"
    with open(test_file, 'w') as f:
        f.write(test_code)

    print(f"\n✓ Generated test file: {test_file.relative_to(PROJECT_ROOT)}")

    # Create conftest.py if it doesn't exist
    conftest_file = test_dir / "conftest.py"
    if not conftest_file.exists():
        conftest_content = '''"""
Pytest configuration for API tests
"""

import pytest
import httpx


@pytest.fixture
def client():
    """HTTP client fixture"""
    return httpx.Client()


@pytest.fixture
def BASE_URL():
    """Base URL fixture"""
    return "http://localhost:8000"
'''
        with open(conftest_file, 'w') as f:
            f.write(conftest_content)

        print(f"✓ Created conftest: {conftest_file.relative_to(PROJECT_ROOT)}")

    # Create __init__.py if it doesn't exist
    init_file = test_dir / "__init__.py"
    if not init_file.exists():
        init_file.touch()
        print(f"✓ Created __init__.py: {init_file.relative_to(PROJECT_ROOT)}")

    print("\n" + "=" * 60)
    print("API Test Generation Complete")
    print("=" * 60)

    return 0


if __name__ == "__main__":
    sys.exit(main())
